eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: service-discovery # Service name

server:
  port: 8761

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
